#!/usr/bin/env bash

[ -f ~/.config/sops/age/keys.txt ] && echo "SOPS keys already exist" && exit 0

mkdir -p ~/.config/sops/age

[ command -v op ] || echo "op is not installed" && exit 1

op read "op://Private/age for sops/age.txt" > ~/.config/sops/age/keys.txt

echo "SOPS keys pulled from 1Password"