#!/usr/bin/env bash
#MISE description="Encrypt a file using sops with the configured age recipient"
#MISE dir="{{cwd}}"

sops encrypt --age "$sops_recipients" "${1:-.env}" --output "${1:-.env}.encrypted"