[tools]
ninja = "latest"
poetry = "latest"
pipx = "latest"
bat = "latest"
exa = "latest"
fd = "latest"
python = "3.11"
node = "latest"
pnpm = "latest"
just = "latest"
zoxide = "latest"
mcfly = "latest"
lazydocker = "latest"
ctop = "latest"
github-cli = "latest"
