GITLAB_USERNAME='CircleOnCircles'
GIT_DEFAULT_BRANCH='main'
GIT_EMAIL='nutchanon@codustry.com'
GIT_NAME='Nutchanon Ninyawee'
GIT_PROTOCOL='https'
GITHUB_USERNAME='wasdee'
GPG_SIGNING_KEY=''
MERGE_TOOL='delta'
